# Generated by Django 2.2.1 on 2019-06-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='url_da_foto',
            field=models.URLField(null=True),
        ),
    ]
