# Generated by Django 2.2.1 on 2019-06-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_artista_url_da_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('gostar', models.IntegerField(default=0)),
                ('naoGostar', models.IntegerField(default=0)),
                ('letra', models.TextField(null=True)),
                ('artistas', models.ManyToManyField(related_name='musicas', to='web.Artista')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='web.Genero')),
            ],
        ),
    ]
