# Generated by Django 2.2.1 on 2019-06-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_musica_url_do_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='url_da_foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='artistas',
            field=models.ManyToManyField(blank=True, related_name='musicas', to='web.Artista'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='letra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='url_do_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
