# Generated by Django 2.2.1 on 2019-06-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190607_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
